env:
 - FINAL_NAME = mongomvc-1.0.0-SNAPSHOT.jar

sudo: required

language: java

services:
  - docker

before_script:
 - mvn clean install -DskipTests
 - cp ./target/$(FINAL_NAME) ./docker
 - docker-compose up -d
 - rm ./docker/$(FINAL_NAME)

script:
 - mvn clean test

after_script:
 - docker-compose down
