version: '3'
services:

   mongomvc:
     build: ./docker
     container_name: mongomvc
     ports:
       - 8080:8080
     depends_on:
       - mongodb


   mongodb:
     image: mongo:latest
     container_name: mongodb
     ports:
       - 27017:27017
     volumes:
       - './dev/data/db:/data/db'
